language: java
jdk:
  - oraclejdk8

sudo: required

dist: trusty

#before_install:
#  - cd floodlight

install:
  - ./.travis/install_dependencies
  - sudo ./.travis/install_ovs
  - sudo ./.travis/start_ovs
  - ./.travis/install_mininet
  - ./.travis/install_mininext

script: sudo python ./mininet/simpletest.py

notifications:
  email: false