language: java
sudo: enabled
dist: trusty
install:
  - sudo ./setup/install_dependencies
  - sudo ./setup/install_ovs
  - sudo ./setup/start_ovs
  - sudo ./setup/install_mininet
  - sudo ./setup/install_mininext
  - sudo ./setup/cleanup