language: java

sudo: enabled

dist: trusty

install:
  - ./.travis/install_dependencies
  - sudo ./.travis/install_ovs
  - sudo ./.travis/start_ovs
  - ./.travis/install_mininet
  - ./.travis/install_mininext

notifications:
  email: false