language: java

sudo: enabled

dist: trusty

install:
  - .travis/install_dependencies
  - .travis/install_ovs
  - .travis/start_ovs
  - .travis/install_mininet
  - .travis/install_mininext
  - .travis/cleanup

notifications:
  email: false