language: java
jdk:
  - oraclejdk8

#sudo: enabled

dist: trusty

before_install:
  - floodlight

install:
#  - ./.travis/install_dependencies
#  - sudo ./.travis/install_ovs
#  - sudo ./.travis/start_ovs
#  - ./.travis/install_mininet
#  - ./.travis/install_mininext

#script: sudo python ./mininet/simpletest.py

notifications:
  email: false